% This function determines whether the cone generated by the discrete control set
% at a point in the simplex A_3 is maximal or not. i.e. there are six generated vectors
% and if these generate a cone that is R^2, the function returns 1, and 0 otherwise.

function [ yup ] = isconemax(x1,x2,w)

% Initialize vector set
v = [];

% Fetch the linear system for one control
[A,b] = A_b_rinf(w);

% Fetch the rep of the symmetric group S3
S3g = S3gen;
for j = 1:6
	
	% Find the other five vectors
    	vtem = S3g(:,:,j)*(b - A*S3g(:,:,j)'*[x1;x2]);

	% Discard vectors that are essentially zero    
	if norm(vtem) > 1e-12
        v = [v,vtem];
    end
end

% Find number of non-trivial vectors and initialize set of angles
vno = size(v,2);
angles = zeros(1,vno);

% If fewer than three vectors are non-trivial, the cone cannot be maximal
if vno <= 2
    yup = 0;
    return
end

% Calculate the angles
for j = 1:vno
    if v(1,j) > 0
        angles(j) = atan(v(2,j)/v(1,j));
    elseif v(1,j)<0
        angles(j) = atan(v(2,j)/v(1,j)) + pi;
    elseif v(2,j) > 0
        angles(j) = pi/2;
    else angles(j) = -pi/2; 
    end
end

% Sort the angles
angles=sort(angles);

% Find the differences between neighboring vectors
anglesep=zeros(1,vno);
for j=1:vno-1
    anglesep(j) = angles(j+1) - angles(j);
end
anglesep(vno) = angles(1)-angles(vno)+2*pi;

% If the maximum difference is pi or greater, return zero
if max(anglesep) < pi
    yup=1;
else yup=0;

end


end
